### PR TITLE
Persist User state on NSUbiquitousKeyValueStore

### PR DESCRIPTION
**Pull request by wayni208**
Since the app is now universal,I wanted to be able to persist user progress between devices. I have tried to accomplish this with NSUbiquitousKeyValueStore, using the same logic @twostraws built into the app for saving to UserDefaults. Its 99% there.

The last issue is, and I hope that you can help steer me into the correct direction to resolve this, that when the app is open on two devices _at the same time_, the trailing device is not updating its UI in response to NSUbiquitousKeyValueStore.didChangeExternallyNotification being observed. Ideally, because having two devices with the app open at the same time is a real probability, the not in use device should update and refresh its tableviews to correspond with the values saved in NSUKVS. Currently, the data is received but the UI does not reflect newest changes. However, if you exit and restart the app, the newest changes will be visible. 

How should I refresh the data to display on the inactive device without exiting the app? reloadData doesn't do anything and I have tried a couple different AppDelegate functions without success. I suspect it has to do with the coordinator pattern being used. I have a couple videos on that subject to watch tomorrow but in the meantime...

### CODE REVIEW

**Comment by wayni208** [comment]
Oops. Sorry. I meant to make this a draft PR.

**Comment by twostraws** [comment]
This is quite a big change fairly late in development; I'm a bit worried about accepting it unless you're sure you've tested it really thoroughly. I'm also concerned that all view controllers now need to care about iCloud, which really ought not to be necessary – we should be able to synchronize user data in one place and simply post `userDataChanged` to have them re-read their data from a central location.

**Comment by wayni208** [comment]
Yes, it is. I would say that persisting this data across multiple devices is necessary. I have both an iPhone and an iPad. I would bet that this is the case for many of us as well. As I view it, you have done a very good job gameifying the app by tracking progress via a score system and badges. It's a blast seeing the scores increase, new badges awarded, and all of the green checkmarks to see our progress. A new Swift developer (such as myself) would have the app going on multiple devices and would derive much pleasure in having their progress displayed and able to build on with whichever app they use. 

Preaching to the Choir here, I'm sure. 😀 I'll test the heck out of it, promise. And if its not something you want to do for release I hope you will consider it for a following update. 

But I do want to go a different direction with this which will likely entail another pull request. If I am not connected to iCloud - no signal, iCloud is turned off, I'm logged out of iCloud - progress will only be retained as long as the app is open. Once closed, it reverts back to the last, good, iCloud sync. I think the preferable way to avoid this behavior is to keep UserDefaults and, if iCloud is available, overwrite UserDefaults only if the iCloud version is newer, send the data to iCloud if not. This should be kind of elementary, I think. 

And I've figured out what needs to happen to get the views updated after returning to foreground. 

This is going to be a complete rewrite of what I have done. Sorry, I really didn't mean to make this a WIP pull request. Would you rather I close this and resubmit after I have everything working as intended or just continue with this one?

**Comment by twostraws** [comment]
> If I am not connected to iCloud - no signal, iCloud is turned off, I'm logged out of iCloud - progress will only be retained as long as the app is open. Once closed, it reverts back to the last, good, iCloud sync.

This is sounding increasingly dangerous – this app needs to go live and have thousands of people using it, so that kind of behavior will just cause problems.

Have you considered a framework designed to remove this problem entirely? I don't want iCloud code scattered all over – the whole `userCloudDataChanged()` method thing just doesn't seem necessarily.

I'm going to take a look at one now – [Zephyr](https://github.com/ArtSabintsev/Zephyr).

**Comment by wayni208** [comment]
@twostraws yes, in fact. Got it working last night with Zephyr. I was going to pretty it up and send today.

**Comment by twostraws** [comment]
Great! Right now I'm busy fixing up the pods used by the project, so you might want to wait for me to make that commit before fixing up this PR.

**Comment by twostraws** [comment]
FYI: I've finished bumping the pods now, so you're all clear to commit.

**Comment by wayni208** [comment]
I don't think I'm doing this right... I had hoped it would haver blitzed everything old...

**Comment by twostraws** [comment]
It might be worth putting your changes to one side and doing a clean PR, if that would help.

**Pull request closed without merging**
