### PR TITLE
Problem in a Daily Challenge question #50

### PR DESCRIPTION
**Pull request by mike011**
Fixes that the constants created do not match the constants used when summing.

Is there a way to test this? The son file is loaded than shuffled? What are the thoughts on having a debug mode that would load and show all the questions? Something as simple as having a long press on the "Predict the Output" button.

### CODE REVIEW

**Comment by rahulrs0029** [comment]
I just tried. This does not fix the issue. 🤷‍♂️ @twostraws

**Comment by mike011** [comment]
Good catch, should be fixed now.

**Comment by mike011** [comment]
simulator screen shot - iphone xs - 2018-11-17 at 11 08 58

**Comment by rahulrs0029** [comment]
Yeah now it's fixed 👍

**Comment by rahulrs0029** [comment]
Like this? @twostraws

**Comment by twostraws** [comment]
Yeah, that’s exactly what I was hoping for! We could even use that for the sum variable too somehow, such as `customerTotal`.

—

**Comment by rahulrs0029** [comment]
Okey. Like this?

**Comment by twostraws** [comment]
Right! Like that 👍

**Comment by rahulrs0029** [comment]
So should I open a new PR or how can I make changes to this PR? @twostraws @mike011

**Comment by twostraws** [comment]
I’m going to merge the current PR and you can open a new one.

**Pull request merged**
