### PR TITLE
Make it a universal app

### PR DESCRIPTION
**Pull request by lunij**
It feels so much better when you can use an iPhone app on an iPad as well. If there are no bigger concerns why this app shouldn't allow universal builds then I like the user to decide which device fits best to use the app.

#29

### CODE REVIEW

**Comment by twostraws** [comment]
I can understand why you might want this, but I think this app would benefit from a great deal more work in order to be a good iPad citizen – just flicking the switch isn't a pleasant experience, and I'm not keen to proceed with a stretched iPhone app.

**Comment by lunij** [comment]
You're right. I'd prefer an experience which is designed for the iPad rather than stretching the iPhone views as well. But this PR only ensures that the experience does not get worse like it is now where you have to use the iPhone sized app on your iPad. I mean, people are still able to install the iPhone app on their iPad. If the switch would prevent them from doing this, I'd agree with you and don't flick the switch without providing a good iPad experience.

**Comment by twostraws** [comment]
I'm going to close this. I went ahead and made the switch to iPad myself just to check it out, and I ended up having to make lots of other changes to make it work well – making the status ring smaller, stopping the tour from being stretched the entire width of the screen (and breaking its Auto Layout constraints), making the badge collection view wrap its cells correctly, and more. So, the end result it works passably on iPad now, but it took a lot more work!

**Comment by lunij** [comment]
Thanks @twostraws for doing this! Looks great now. 🎉

**Pull request closed without merging**
