### PR TITLE
Tour grammar fix

### PR DESCRIPTION
**Pull request by SuzGupta**
Hopefully this works as intended, I am very much a newbie: am trying to submit a small grammar fix for the Tour JSON and not submit the project files changed to allow me to build locally. Please help me learn how to do this better :)

### CODE REVIEW

**Comment by demianturner** [comment]
Hi @SuzGupta - if you use a git client like the free app SourceTree, it's very easy to select which files are added to your commit.  You have indeed included your .xcodeproj and other changes in this PR which are not relevant to your fix.

**Comment by imvm** [comment]
If it's not relevant, why not add it to the project's .gitignore?

**Comment by demianturner** [comment]
@imvm The Xcode project file is relevant to the Unwrap repo, but it's not relevant to @SuzGupta's PR because she doesn't need to add or delete any files, she just changed the text in a json file.

**Comment by imvm** [comment]
Ahhh I see, thanks for the explanation.

**Comment by SuzGupta** [comment]
@demianturner @imvm Thank you both for commenting. I am a newbie to this (contributing to iOS apps on GitHub) and was hoping to be able to do this via just Xcode 9 and GitHub, but let me read up on what one does with a .gitignore file and see if I could understand where SourceTree (which I do have but have not used for years and never understood well). Further explanation welcome. (I'll close this and submit a new PR hopefully this afternoon.)

**Comment by bmeverett** [comment]
@SuzGupta so basically you want to only _stage_ the file you want to commit to the repo. A `.gitignore` is only for files you always want to ignore which we don't want to do here. 

Here are some screenshots from SourceTree to hopefully help you understand what is going on.

First you want to stage the file to be committed. In your case it would be `Tour.json`. Just click stage this file and it'll move to the top section which is the staging area.

screen shot 2018-08-22 at 5 01 13 pm



screen shot 2018-08-22 at 5 07 29 pm


All other files not relevant (`.xcodeproj`) can be left unstaged. Then you can type a commit message and push to your branch. It will only commit the staged files. 

Hope this helps!!

**Pull request closed without merging**
