### PR TITLE
Add and implement 'Zephyr' as a pod

### PR DESCRIPTION
**Pull request by wayni208**
Added 'Zephyr' to podfile. Deleted 'Zephyr.swift' from User folder.

### CODE REVIEW

**Comment by twostraws** [comment]
Good job!

**Comment by wayni208** [comment]
Thank you. 🙂 

Any idea why did the bitrise fails?

**Comment by twostraws** [comment]
Nope! I've emailed them; maybe we'll know soon.

**Comment by wayni208** [comment]
Ok! Is there anything else I can help with?

**Comment by twostraws** [comment]
At this point I really just need to get the thing out! I'll try to issue a fresh TestFlight build in the morning so folks can start trying out the iCloud work you've done. If you were really keen to try something, perhaps #30? In theory it should be just a matter of adding an extra line of text to the alerts on the home screen, something like "Progress: 75%".

**Comment by wayni208** [comment]
Ok! I'll give it a shot!

**Comment by wayni208** [comment]
Simulator Screen Shot - iPhone Xʀ - 2019-04-25 at 21 54 50
 
Is this what you might be after?

**Comment by wayni208** [comment]
Simulator Screen Shot - iPhone Xʀ - 2019-04-25 at 21 54 50

Like this?

**Pull request merged**
