### PR TITLE
Update FreeCoding.json

### PR DESCRIPTION
**Pull request by l-rettberg**
Added solution for five (5) problems to allow single line function without use of "return".

### CODE REVIEW

**Comment by twostraws** [comment]
Sorry, I'm only now getting around to looking at this. Rather than adding extra entries for all possible tests, I wonder if it's possible to use something like `letvar` to mean "you can use return here but it isn't needed." Maybe `optionalreturn`? That way we don't add more strings to be checked, and it gets resolved in code for everything now and in the future.

**Comment by Carrione** [comment]
I will prepare the code for using the optionalreturn keyword in the new PR.

**Comment by Carrione** [comment]
Code for using the optionalreturn keyword in free coding - see PR  #174

**Comment by twostraws** [comment]
Can this now be closed?

**Comment by l-rettberg** [comment]
Closing this PR - as it's superseded by PR #174

**Pull request closed without merging**
