### PR TITLE
Dealing with the '…' ellipsis issue by homogenising to three periods

### PR DESCRIPTION
**Pull request by robinlmp**
I hope I've done this right. I've largely followed the pattern of other similar homogenising blocks so hopefully it is ok. If not, would be interesting to see where I've made mistakes.

### CODE REVIEW

**Comment by Carrione** [comment]
Related to #215

**Comment by twostraws** [comment]
Should we be adding the extra spacing around "..."? That is, right now you're changing to " ... " rather than "..." and I'm curious why.

**Comment by robinlmp** [comment]
I was following the example a few lines above where a different function was adding spacing. Perhaps as that already exists and adds the spaces, it shouldn't be duplicated with this one?

Screenshot 2021-09-17 at 12 59 11

**Comment by twostraws** [comment]
Ah, right! Yes, that makes sense; it homogenizes the spacing, but that won't have happened for the ellipsis character. Thank you! I'll merge this now.

**Pull request merged**
