### PR TITLE
User var and reduce warning fix

### PR DESCRIPTION
**Pull request by anibalrodriguez**

### CODE REVIEW

**Comment by twostraws** [comment]
Thank you for your contribution! The change to `allSatisfy()` is a welcome one, but I'd rather leave the `lazy` variable alone – the warning there is Swift's problem, not ours. Can you push a change without that?

**Comment by twostraws** [comment]
Awesome – thank you!

**Comment by anibalrodriguez** [comment]
Np, happy to help. I liked this project, Thank you!

**Comment by BasThomas** [comment]
> the warning there is Swift's problem, not ours. Can you push a change without that?

Would be nice to create a Swift bug for, though ;)

**Comment by twostraws** [comment]
There is already a bug report for it: https://bugs.swift.org/browse/SR-10646 – I believe it's resolved now.

**Pull request merged**
