### PR TITLE
Added 2 new answers for a Free Coding Question.

### PR DESCRIPTION
**Pull request by rahulrs0029**
Added 2 new answers for a Free Coding Question, in which user has type code that doubles all the elements of an array.

I'm working to add 4-5 more new answers to the same question.

### CODE REVIEW

**Comment by rahulrs0029** [comment]
Yeah! I am also confused about that indent. 🤷‍♂️

It looks fine in Xcode though. I've try re-indenting by pressing **Control + I** in Xcode but no changes.

**Comment by twostraws** [comment]
Is it a tabs vs spaces issue?

**Comment by rahulrs0029** [comment]
Sorry, I don't know why that is happening. 🤷‍♂️

**Comment by twostraws** [comment]
OK; I'll merge and investigate. Thank you!

**Comment by rahulrs0029** [comment]
Oh I see!
Can you tell me how you fixed that indent? so that I can make sure that my future PRs don’t have this indent problem 😃

**Comment by rahulrs0029** [comment]
@twostraws I tried added 2 new answers to the same question. They are also indented differently.
Can you tell me how you fixed that indent issue so that I can make my next PR? 😀

**Comment by twostraws** [comment]
I used Sublime Text, which lets me control the whitespace more easily. In Xcode, try going to Editor > Show Invisibles, which will show you how the spaces are made.

**Comment by rahulrs0029** [comment]
I changed my Xcode preference from Indent using Spaces to Indent using Tabs and it was fixed :) Thanks!

**Pull request merged**
