### PR TITLE
FreeCoding.json update - Other variants of the correct answer.

### PR DESCRIPTION
**Pull request by Carrione**
This is the solution to the problem mentioned on [slack](https://hackingwithswift.slack.com/archives/CJBQQ7J4C/p1626163028064300). The solution using the method hasPrefix can accept a parameter with a whitespace.

### CODE REVIEW

**Comment by twostraws** [comment]
Rather than duplicating all those answers, do you think this could perhaps be solved with a regular expression?

**Comment by Carrione** [comment]
@twostraws Ok. I'll update this PR.

**Comment by twostraws** [comment]
Is this still underway?

**Comment by Carrione** [comment]
Hi Paul, I have it listed as one of my assignments. I've recently been held up by my medical situation. Please bear with me.

**Comment by twostraws** [comment]
There's no rush! I've just been busy doing some spring cleaning and wanted to check in 👍

**Comment by Carrione** [comment]
I closed it. I noticed that the suggested answers were causing problems in the preparation of the regular expression. We would have to restrict the execution of line 131 in FreeCodingPractice.swift.

**Pull request closed without merging**
