### PR TITLE
Added new answers for a Free Coding Question.

### PR DESCRIPTION
**Pull request by rahulrs0029**
I've added more new answers to one Free Coding question.

I've only committed 2 of them right now.
But I've made a playground file which has all the answers/methods: [DoubleAnArray.playground](https://github.com/twostraws/Unwrap/files/2595168/DoubleAnArray.playground.zip)

Can you take a look at it whenever you get some time? @twostraws 

Tell me if any of these shouldn't be added, and I'll add the rest of those in future commits.

### CODE REVIEW

**Comment by twostraws** [comment]
From memory, I think a few of these can be removed – doesn't Unwrap normalize `Array<Int>` to be `[Int]`? We could probably do a couple of other normalizations to reduce the number of possible matches – that's a better long-term solution than just adding more and more text for the same problem.

**Comment by rahulrs0029** [comment]
Yes. That’s why I didn’t committed all of them. Like there are 3 ways to declare an array, and 3 ways to double the elements (using for loop, map, and forEach). It would be better to use normalization

**Comment by twostraws** [comment]
In this instance I'm not too worried about `forEach` – if someone knew enough to use that, they'd realize that `map` was the correct choice. Take a look at normalization and see what you can figure out, because it would benefit lots of other places too!

**Comment by rahulrs0029** [comment]
Thanks. I will!

**Pull request closed without merging**
