### PR TITLE
Update Pods

### PR DESCRIPTION
**Pull request by DevboiDesigns**
update to pods and version

### CODE REVIEW

**Comment by twostraws** [comment]
There are all sorts of storyboard changes here, so I'm rather wary of merging this in. Could you perhaps elaborate what changed and why?

**Comment by DevboiDesigns** [comment]
When I downloaded it there were updates that Xcode was asking for, that is all i did to it was accept those changes. It was building fine then, however i just build it now and getting error that "SwiftEntryKit isnt a module".

**Comment by twostraws** [comment]
Hmm… build errors definitely sound bad 😅   Do you want to try to fix them, or should I close this PR?

**Comment by DevboiDesigns** [comment]
maybe can you give me a few days and let me see if i can? i would love to try anyway

**Comment by twostraws** [comment]
Great! As an alternative, I wonder whether you might like to take on a fewer more specific tasks I have in mind that would be suitable for first-time contributors? Let me know 🙌

**Comment by DevboiDesigns** [comment]
That sounds great, yes please! 😃

**Comment by twostraws** [comment]
Sorry for taking so long! I've created various issues that might be of interest. From easiest to hardest they are:

- #197 
- #196 
- #194
- #195

**Comment by DevboiDesigns** [comment]
Ok great! I got an entry level/ trial basis opportunity so I will jump on this right after. I had to learn UIKit, so will help with this project too. Thanks Paul

**Pull request closed without merging**
