### PR TITLE
Remove level-up chime to prevent background audio interruption

### PR DESCRIPTION
**Pull request by almaleh**
Currently, the level up chime completely stops any music/podcast I have playing in the background. 

This pull request resumes the background audio after the chime has finished playing. 

p.s: I considered using the .mixWithOthers category option to have both the chime and background audio play simultaneously, but this is not optimal for the videos

### CODE REVIEW

**Comment by twostraws** [comment]
Hi Besher! Thank you for this contribution. I think perhaps we should just remove the level up sound entirely – having music fade in and out might seem just as bad as making it stop. Do you want to open a PR to remove the sound file / playback entirely?

**Comment by almaleh** [comment]
> Hi Besher! Thank you for this contribution. I think perhaps we should just remove the level up sound entirely – having music fade in and out might seem just as bad as making it stop. Do you want to open a PR to remove the sound file / playback entirely?

Hi Paul, yes I agree it can be annoying. 

I could certainly remove the chime, I'll update the PR accordingly

**Comment by almaleh** [comment]
I removed the level up chime but left the haptic feedback, as that one doesn't affect background audio

It's ready for merge :)

**Comment by twostraws** [comment]
Perfect – thank you!

**Pull request merged**
