### PR TITLE
Zephyr implementation to persist UserDefaults to iCloud

### PR DESCRIPTION
**Pull request by wayni208**
Added Zephyr into the User directory because I modified its source to call into User and kick off the userDataChanged notification.

### CODE REVIEW

**Comment by twostraws** [comment]
Is this ready to merge?

**Comment by wayni208** [comment]
Yes sir

**Comment by twostraws** [comment]
Great! I'm going to do a little clean up here, and try to post a PR to Zephyr with a notification that we can catch – that would allow us to use Zephyr as a pod rather than copying in its source code.

**Comment by wayni208** [comment]
Awesome! I can’t wait to see what you do!

**Comment by twostraws** [comment]
Argh; I had forgotten how annoying it was testing iCloud! 😅

I have cleaned up the code, but something else is now worrying me: does this handle syncing the user's streak between devices? I'm concerned that one device will overwrite the other very easily.

**Comment by wayni208** [comment]
I was going to ask if that’s why you say it’s unpleasant to work with. I find it takes a lot of awareness to make sure both testing platforms are _just right_ or it gets finicky. 

I didn’t consider the streak. I’ll test that tonight. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wayni208** [comment]
It does sync the streak and it does cause things to go into a loop, each device overwriting the other, when I roll the time around on one device. 

I think I have it fixed. I’m going to sleep on these changes and see what happens during a normal calendar day rollover. If everything checks out I’ll send a PR in the morning. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wayni208** [comment]
It works!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
