### PR TITLE
FreeCoding.json update and new func to homogenize guard statements + tests

### PR DESCRIPTION
**Pull request by Carrione**

### CODE REVIEW

**Comment by twostraws** [comment]
I can't merge this in – it's a huge change, and you haven't actually said what you're trying to do. Can you elaborate, or perhaps break up the changes into more than one PR?

**Comment by Carrione** [comment]
The essence of this PR is primarily an effort to expand the possible range of answers. Among the answers, I also included variants containing guard statements. However, this created a requirement for homogenization of these statements, because otherwise, it would be necessary to extend the answers with variants of the same working with line breaks in else branches of guard statements. Homogenization also solves the correct targeting of the response processing only to the relevant guard statement, so that its other parts, such as if statements are not inadvertently affected.

From the above, it is clear that this PR can be divided into two separate parts. However, my effort is rather to minimize the number of PRs. However, if you prefer to split this PR after my answer, I will of course do so :).

**Comment by twostraws** [comment]
It looks like several things are being addressed at once, which is an issue because of #167 also addressing the `return` statement thing. As I said in a comment there, I think a more flexible `optionalreturn` keyword, similar to `letvar`, would give us some extra flexibility without needing to add extra answers.

**Comment by Carrione** [comment]
OK. I will prepare the code for using the optionalreturn keyword in the new PR and change this one accordingly. I will also unify this one with #167.

**Comment by Carrione** [comment]
Code for using the optionalreturn keyword in free coding - see PR  #174

**Comment by Carrione** [comment]
This PR is replaced by new ones. Homogenization of guard statements is solved by PR #176

**Pull request closed without merging**
