### PR TITLE
Changed 'bundleNameSections' from lazy var to a computed property

### PR DESCRIPTION
**Pull request by RorySlingo**

### CODE REVIEW

**Comment by twostraws** [comment]
Hello! Thank you for your contribution. Having a lazy property is a performance enhancement – could you perhaps add some explanation of why we would want to remove it?

**Comment by RorySlingo** [comment]
A lazy property has a mutable getter which means the Chapter struct must be assigned as a var to access `bundleNameSections`

But doing `guard var conditionChapter = Unwrap.chapters.first(...` gives the compiler warning `Variable 'conditionChapter' was never mutated; consider changing to 'let' constant` which we are annoyed by.

And we can't make it a 'let' constant as the compiler then reminds us `Cannot use mutating getter on immutable value: 'conditionChapter' is a 'let' constant`

Since `bundleNameSections` is only replacing characters in an array of strings and Chapters are instantiated once in the whole app, I'd argue that it's relatively inexpensive to compute upon initialisation vs making it lazy. Making it a computed property gets rid of both compiler warning and error.

There are a few alternatives:
1. Keep it a lazy var and make Chapter a class instead of a struct. Doesn't seem the right choice just to make compiler warnings go away.

2. Make `bundleNameSections` a method instead of a variable. Same performance as lazy var ie. only computed when called. Mildly uglier at the call site. I would go for this if making it a computed property is not preferable.

3. `bundleNameSections` is literally only called in one place, in User.swift. Just remove this property  and unroll it directly at the call site. `chapter.bundleNameSections().map(hasReviewed)` would become `chapter.sections.map{$0.bundleName}.map(hasReviewed)`. This loses future reusability though.

**Comment by twostraws** [comment]
The warning/error situation is a bug in Swift, not in Unwrap. See here: https://bugs.swift.org/browse/SR-10123

**Comment by RorySlingo** [comment]
Aha, well the file did say //FIXME so I attempted to :p Can discard this then if you like.

**Comment by twostraws** [comment]
I think we'd best wait to see how pans out on the Swift front first. Hopefully the problem will be resolved by them!

**Pull request closed without merging**
