### PR TITLE
Update code to Swift 4.2

### PR DESCRIPTION
**Pull request by verebes1**
Code updated to Swift 4.2 across the whole app. Tested on my phone runs smoothly.

### CODE REVIEW

**Comment by verebes1** [comment]
Yes I am up to date with it.
just updated before creating the pull requests. However by looking into it in more detail it looks like the Pods were the ones that Xcode has updated to 4.2

**Comment by twostraws** [comment]
You can't be up to date – GitHub is saying there are merge conflicts all over the place, which means you're trying to change files that have already been changed.

**Comment by verebes1** [comment]
My PodFiles were not up to date probably that was why. Weird as I did  a full merge from your repo before doing any changes.

**Comment by verebes1** [comment]
I did recreate a fork of your repo again and Xcode is still yelling that there is a Swift Conversion available however it is pointing out the pods. There are very minimal changes to your code. Just to get rid of warnings.

**Comment by twostraws** [comment]
You shouldn't need to touch the pods – they are already bundled, and can be
left alone.

--

**Pull request closed without merging**
